---
# https://packit.dev/docs/configuration/


files_to_sync:
  - src:
      - ".packit.yaml"
      - "build/package/rpm/go-fdo-server.spec"
      - "build/package/rpm/go-vendor-tools.toml"
      - "build/package/rpm/go-fdo-server-*-vendor.tar.bz2"
    dest: .

upstream_package_name: go-fdo-server
downstream_package_name: go-fdo-server

upstream_tag_template: v{version}
copy_upstream_release_description: true

srpm_build_deps:
  - curl
  - git
  - make
  - bison
  - gcc
  - glibc-devel
  - golang
  - go-vendor-tools
  - python3-tomlkit
  - askalono-cli

packages:
  go-fdo-server-fedora:
    downstream_package_name: go-fdo-server
    upstream_package_name: go-fdo-server
    specfile_path: build/package/rpm/go-fdo-server.spec
  go-fdo-server-centos:
    downstream_package_name: go-fdo-server
    upstream_package_name: go-fdo-server
    pkg_tool: centpkg
    specfile_path: build/package/rpm/go-fdo-server.spec

actions:
  fix-spec-file:
    - |
      bash -c '
      #! /bin/bash
      export BASE_DIR=build/package/rpm
      export SPEC_FILE=${BASE_DIR}/go-fdo-server.spec
      # We need the full commit hash
      export COMMIT=$(git rev-parse ${PACKIT_PROJECT_COMMIT})
      sed -i "s/^%global commit\(\s*\).*/%global commit\1${COMMIT}/" ${SPEC_FILE}
      sed -i "s/^Version:\(\s*\).*/Version\:\1${PACKIT_PROJECT_VERSION}/" ${SPEC_FILE}
      sed -i "s/^Release:\(\s*\)\S+/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/" ${SPEC_FILE}
      '
  post-modifications:
    # https://fedora.gitlab.io/sigs/go/go-vendor-tools/scenarios/#manual-update
    - |
      bash -c '
      #! /bin/bash
      set -x
      export GOTOOLCHAIN=auto
      export BASE_DIR=${PACKIT_UPSTREAM_REPO}/build/package/rpm
      export GO_VENDOR_TOOLS_CONFIG=${BASE_DIR}/go-vendor-tools.toml
      export SPEC_FILE=${BASE_DIR}/go-fdo-server.spec
      go_vendor_archive create --config ${GO_VENDOR_TOOLS_CONFIG} ${SPEC_FILE}
      go_vendor_license \
        --config ${GO_VENDOR_TOOLS_CONFIG} \
        --path ${SPEC_FILE} \
        report \
        --verify-spec
      '

jobs:

  # Fedora jobs

  - &fdo_copr_build_fedora
    job: copr_build
    packages: [go-fdo-server-fedora]
    trigger: pull_request
    targets:
      fedora-branched:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/fedora-$releasever-$basearch/
        additional_packages:
          - golang
      fedora-rawhide:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/fedora-rawhide-$basearch/
        additional_packages:
          - golang


  - <<: *fdo_copr_build_fedora
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot


  - job: sync_from_downstream
    trigger: commit

  - job: propose_downstream
    trigger: release
    packages: [go-fdo-server-fedora]
    dist_git_branches: ["fedora-development", "fedora-stable"]

  - job: koji_build
    trigger: commit
    allowed_pr_authors: [all_committers]
    dist_git_branches: ["fedora-development", "fedora-stable"]

  - job: bodhi_update
    trigger: commit
    allowed_builders: [all_committers]
    dist_git_branches: ["fedora-development", "fedora-stable"]

  # Fedora E2E Testing jobs

  - job: tests
    trigger: pull_request
    identifier: e2e-fedora
    tmt_plan: test/fmf/plans/e2e
    packages: [go-fdo-server-fedora]
    targets:
      - fedora-latest-stable
      - fedora-latest
      - fedora-rawhide

  # CentOS jobs

  - &fdo_copr_build_centos
    job: copr_build
    packages: [go-fdo-server-centos]
    trigger: pull_request
    targets:
      epel-9:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/epel-9-$basearch/
        additional_packages:
          - golang
      epel-10:
        additional_repos:
          - https://download.copr.fedorainfracloud.org/results/@go-sig/golang-rawhide/epel-10-$basearch/
        additional_packages:
          - golang

  - <<: *fdo_copr_build_centos
    trigger: commit
    branch: main
    owner: "@fedora-iot"
    project: fedora-iot

  # CentOS E2E Testing jobs
  #
  - job: tests
    trigger: pull_request
    identifier: e2e-centos
    tmt_plan: test/fmf/plans/e2e
    packages: [go-fdo-server-centos]
    targets:
      - epel-9
      - epel-10
